isall: false
url: ''
selectors: 'select#edit-field-hp-s5-stories'
placeholder_text: ''
filtertype: partial
js_regex: false
orderable: false
groupresetfilter: false
remove_required_attr: false
buttontext_add: '>'
buttontext_addall: »
buttontext_del: '<'
buttontext_delall: «
buttontext_moveup: 'Move up'
buttontext_movedown: 'Move down'
langcode: ar
