entity_type_groups:
  node:
    course:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    faq:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    home_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
    story:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    webform:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
  path_alias:
    path_alias:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
  taxonomy_term:
    tags:
      basic: basic
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
